<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: sans-serif;
            line-height: 1.6;
            color: #333;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .header {
            background: #6932BB;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
        }

        .content {
            padding: 30px;
            border: 1px solid #e5e7eb;
            border-top: none;
            border-radius: 0 0 8px 8px;
        }

        .button {
            display: inline-block;
            padding: 12px 24px;
            background: #6932BB;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            font-weight: bold;
            margin-top: 20px;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
            color: #9ca3af;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>New Invoice</h1>
        </div>
        <div class="content">
            <p>Dear {{ $invoice->client_name }},</p>
            <p>We have generated a new invoice for you. Please find the details below:</p>

            <table style="width: 100%; margin: 20px 0;">
                <tr>
                    <td style="color: #6b7280;">Invoice Number:</td>
                    <td style="font-weight: bold;">{{ $invoice->invoice_number }}</td>
                </tr>
                <tr>
                    <td style="color: #6b7280;">Date:</td>
                    <td style="font-weight: bold;">{{ \Carbon\Carbon::parse($invoice->invoice_date)->format('M d, Y') }}
                    </td>
                </tr>
                <tr>
                    <td style="color: #6b7280;">Total Amount:</td>
                    <td style="font-weight: bold; font-size: 18px; color: #6932BB;">
                        ₹{{ number_format($invoice->total, 2) }}</td>
                </tr>
            </table>

            <p>The PDF copy of the invoice is attached to this email.</p>

            <p>Thank you for your business!</p>

            <p>Best regards,<br>{{ $invoice->sender_name }}</p>
        </div>
        <div class="footer">
            Generated by Invoicer &bull; {{ $invoice->sender_name }}
        </div>
    </div>
</body>

</html>